### ISSUE TITLE
Auto-detect whether search plugin is enabled

### ISSUE THREAD

**Issue by durera** [durera/mkdocs-carbon#1]
### Feature and motivation

Hide the search bar if the search plugin is disabled, e.g. with this config:

```
plugins:
  - glightbox:
      shadow: true
      caption_position: bottom
      auto_caption: true
      touchNavigation: false
      background: black
```

To enable search we would need to add `search: {}` to the list of plugins.

### Usage example

Obviously, to eliminate what would be a broken search feature in the site if the search plugin is disabled :)
